In [143]:
person = {
    "first": "Mansi",
    "last": "Kothari",
    "email": "mansikothari46@gmail.com"
}

In [144]:
people = {
    "first": ["Mansi"],
    "last": ["Kothari"],
    "email": ["mansikothari46@gmail.com"]
}

In [145]:
people = {
    "first": ["Mansi", "Manan", "Komal", "Sujal"],
    "last": ["Kothari", "Jain", "Kothari", "Jain"],
    "email": ["mansikothari46@gmail.com", "kotharimanan46@gmail.com", "komalexample@gmail.com", "sujalexample@gmail.com"]
}

In [146]:
people['email']

['mansikothari46@gmail.com',
 'kotharimanan46@gmail.com',
 'komalexample@gmail.com',
 'sujalexample@gmail.com']

In [147]:
import pandas as pd

In [148]:
df = pd.DataFrame(people)

In [149]:
df

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
1  Manan     Jain  kotharimanan46@gmail.com
2  Komal  Kothari    komalexample@gmail.com
3  Sujal     Jain    sujalexample@gmail.com

In [150]:
df['email']

0    mansikothari46@gmail.com
1    kotharimanan46@gmail.com
2      komalexample@gmail.com
3      sujalexample@gmail.com
Name: email, dtype: str

In [151]:
type(df['email'])

pandas.Series

In [152]:
df.email

0    mansikothari46@gmail.com
1    kotharimanan46@gmail.com
2      komalexample@gmail.com
3      sujalexample@gmail.com
Name: email, dtype: str

In [153]:
df[["last","email"]]

      last                     email
0  Kothari  mansikothari46@gmail.com
1     Jain  kotharimanan46@gmail.com
2  Kothari    komalexample@gmail.com
3     Jain    sujalexample@gmail.com

In [154]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [155]:
df.iloc[0]

first                       Mansi
last                      Kothari
email    mansikothari46@gmail.com
Name: 0, dtype: str

In [156]:
df.iloc[[0, 2]]

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
2  Komal  Kothari    komalexample@gmail.com

In [157]:
df.iloc[[0, 1], [1, 2]]

      last                     email
0  Kothari  mansikothari46@gmail.com
1     Jain  kotharimanan46@gmail.com

In [158]:
df

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
1  Manan     Jain  kotharimanan46@gmail.com
2  Komal  Kothari    komalexample@gmail.com
3  Sujal     Jain    sujalexample@gmail.com

In [159]:
df.loc[0]

first                       Mansi
last                      Kothari
email    mansikothari46@gmail.com
Name: 0, dtype: str

In [160]:
df.loc[[2, 3]]

   first     last                   email
2  Komal  Kothari  komalexample@gmail.com
3  Sujal     Jain  sujalexample@gmail.com

In [161]:
df.loc[[2, 3], 'email']

2    komalexample@gmail.com
3    sujalexample@gmail.com
Name: email, dtype: str

In [162]:
df.loc[[2, 3], ['first','last']]

   first     last
2  Komal  Kothari
3  Sujal     Jain

In [163]:
df

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
1  Manan     Jain  kotharimanan46@gmail.com
2  Komal  Kothari    komalexample@gmail.com
3  Sujal     Jain    sujalexample@gmail.com

In [164]:
df.set_index('email', inplace=True)

In [165]:
df

                          first     last
email
mansikothari46@gmail.com  Mansi  Kothari
kotharimanan46@gmail.com  Manan     Jain
komalexample@gmail.com    Komal  Kothari
sujalexample@gmail.com    Sujal     Jain

In [166]:
df.index

Index(['mansikothari46@gmail.com', 'kotharimanan46@gmail.com',
       'komalexample@gmail.com', 'sujalexample@gmail.com'],
      dtype='str', name='email')

In [167]:
df.loc['komalexample@gmail.com']

first      Komal
last     Kothari
Name: komalexample@gmail.com, dtype: str

In [168]:
df.iloc[2]

first      Komal
last     Kothari
Name: komalexample@gmail.com, dtype: str

In [169]:
df.reset_index(inplace=True)
df

                      email  first     last
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3    sujalexample@gmail.com  Sujal     Jain

In [170]:
df

                      email  first     last
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3    sujalexample@gmail.com  Sujal     Jain

In [171]:
df.columns

Index(['email', 'first', 'last'], dtype='str')

In [182]:
df.columns = ['first_name', 'last_name', 'email_address']

In [183]:
df.columns

Index(['first_name', 'last_name', 'email_address'], dtype='str')

In [184]:
df

                 first_name last_name email_address
0  mansikothari46@gmail.com     Mansi       Kothari
1  kotharimanan46@gmail.com     Manan          Jain
2    komalexample@gmail.com     Komal       Kothari
3    sujalexample@gmail.com     Sujal          Jain

In [186]:
df.columns = [x.upper() for x in df.columns]
df

                 FIRST_NAME LAST_NAME EMAIL_ADDRESS
0  mansikothari46@gmail.com     Mansi       Kothari
1  kotharimanan46@gmail.com     Manan          Jain
2    komalexample@gmail.com     Komal       Kothari
3    sujalexample@gmail.com     Sujal          Jain

In [188]:
df.columns = df.columns.str.replace('_', ' ')
df

                 FIRST NAME LAST NAME EMAIL ADDRESS
0  mansikothari46@gmail.com     Mansi       Kothari
1  kotharimanan46@gmail.com     Manan          Jain
2    komalexample@gmail.com     Komal       Kothari
3    sujalexample@gmail.com     Sujal          Jain

In [189]:
df.columns = df.columns.str.replace(' ', '_')
df

                 FIRST_NAME LAST_NAME EMAIL_ADDRESS
0  mansikothari46@gmail.com     Mansi       Kothari
1  kotharimanan46@gmail.com     Manan          Jain
2    komalexample@gmail.com     Komal       Kothari
3    sujalexample@gmail.com     Sujal          Jain

In [191]:
df.columns = [x.lower() for x in df.columns]
df

                 first_name last_name email_address
0  mansikothari46@gmail.com     Mansi       Kothari
1  kotharimanan46@gmail.com     Manan          Jain
2    komalexample@gmail.com     Komal       Kothari
3    sujalexample@gmail.com     Sujal          Jain

In [194]:
df.rename(columns={'first_name':'first', 'last_name': 'last', 'email_address':'email'}, inplace=True)

In [209]:
df

                      email   last    first
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3       johnsmith@gmail.com  Smith     John

In [205]:
df.loc[3] = ['johnsmith@gmail.com', 'Smith', 'John']

In [206]:
df

                      email   last    first
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3       johnsmith@gmail.com  Smith     John

In [200]:
df.rename(columns={'first':'email', 'email':'first'}, inplace=True)

In [207]:
df

                      email   last    first
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3       johnsmith@gmail.com  Smith     John

In [226]:
df.columns

Index(['email', 'last', 'first'], dtype='str')

In [228]:
df.at[3, 'email'] = 'john@example.com'
df

                      email   last    first
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3          john@example.com   jain    sujal

In [232]:
filt = (df['email'] == 'john@example.com')
df[filt]['last'] = 'smith'

C:\Users\SHREE\AppData\Local\Temp\ipykernel_3872\238287783.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filt]['last'] = 'smith'

In [233]:
df

                      email   last    first
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3          john@example.com   jain    sujal

In [234]:
filt = (df['email'] == 'john@example.com')
df.loc[filt, 'last'] = 'smith'
df

                      email   last    first
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3          john@example.com  smith    sujal

In [239]:
df['email'] = df['email'].str.upper()
df

                      email   last    first
0  MANSIKOTHARI46@GMAIL.COM  Mansi  Kothari
1  KOTHARIMANAN46@GMAIL.COM  Manan     Jain
2    KOMALEXAMPLE@GMAIL.COM  Komal  Kothari
3          JOHN@EXAMPLE.COM  smith    sujal

In [240]:
df['email'] = df['email'].str.lower()
df

                      email   last    first
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3          john@example.com  smith    sujal

In [241]:
df['email'].apply(len)

0    24
1    24
2    22
3    16
Name: email, dtype: int64

In [243]:
df['last'].apply(len)

0    5
1    5
2    5
3    5
Name: last, dtype: int64

In [244]:
def update_email(email):
    return email.upper()

In [246]:
df['email'].apply(update_email)

0    MANSIKOTHARI46@GMAIL.COM
1    KOTHARIMANAN46@GMAIL.COM
2      KOMALEXAMPLE@GMAIL.COM
3            JOHN@EXAMPLE.COM
Name: email, dtype: str

In [248]:
df['email'] = df['email'].apply(update_email)
df

                      email   last    first
0  MANSIKOTHARI46@GMAIL.COM  Mansi  Kothari
1  KOTHARIMANAN46@GMAIL.COM  Manan     Jain
2    KOMALEXAMPLE@GMAIL.COM  Komal  Kothari
3          JOHN@EXAMPLE.COM  smith    sujal

In [249]:
df['email'] = df['email'].apply(lambda x: x.lower())
df

                      email   last    first
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3          john@example.com  smith    sujal

In [252]:
df.apply(len, axis='columns')

0    3
1    3
2    3
3    3
dtype: int64

In [253]:
df.apply(pd.Series.min)

email    john@example.com
last                Komal
first                Jain
dtype: str

In [254]:
df.apply(lambda x: x.min())

email    john@example.com
last                Komal
first                Jain
dtype: str

In [257]:
df.map(len)

   email  last  first
0     24     5      7
1     24     5      4
2     22     5      7
3     16     5      5

In [265]:
df.map(str.upper)

                      email   last    first
0  MANSIKOTHARI46@GMAIL.COM  MANSI  KOTHARI
1  KOTHARIMANAN46@GMAIL.COM  MANAN     JAIN
2    KOMALEXAMPLE@GMAIL.COM  KOMAL  KOTHARI
3          JOHN@EXAMPLE.COM  SMITH    SUJAL

In [279]:
df['first'] = ['Mansi', 'Manan', 'Komal', 'smith']
df['last'] = ['Kothari', 'Jain', 'Jain', 'Kothari']
df

                      email     last  first
0  mansikothari46@gmail.com  Kothari  Mansi
1  kotharimanan46@gmail.com     Jain  Manan
2    komalexample@gmail.com     Jain  Komal
3          john@example.com  Kothari  smith

In [280]:
df['first'] = df['first'].map({'Mansi':'dolly', 'Manan':'ramu', 'smith':'sujal', 'Komal': 'kamli'})
df

                      email     last  first
0  mansikothari46@gmail.com  Kothari  dolly
1  kotharimanan46@gmail.com     Jain   ramu
2    komalexample@gmail.com     Jain  kamli
3          john@example.com  Kothari  sujal

In [282]:
df['first'] = df['first'].replace({'sujal':'shamu'})
df

                      email     last  first
0  mansikothari46@gmail.com  Kothari  dolly
1  kotharimanan46@gmail.com     Jain   ramu
2    komalexample@gmail.com     Jain  kamli
3          john@example.com  Kothari  shamu