In [3]:
import pandas as pd
import numpy as np

In [20]:
people = {
    "first": ["Mansi", "Manan", "Komal", "Sujal", 'Chris', np.nan, 'NA'],
    "last": ["Kothari", "Jain", "Kothari", "Jain", None, np.nan, "Missing"],
    "email": ["mansikothari46@gmail.com", "kotharimanan46@gmail.com", None, "sujalexample@gmail.com", 'chris@gamil.com', np.nan, 'NA'],
    "age": ['19', '16', np.nan, '18', '50', None, 'Missing']
}

In [34]:
df = pd.DataFrame(people)
df.replace('NA', np.nan, inplace = True)
df.replace('Missing', np.nan, inplace = True)

   first     last                     email  age
0  Mansi  Kothari  mansikothari46@gmail.com   19
1  Manan     Jain  kotharimanan46@gmail.com   16
2  Komal  Kothari                       NaN  NaN
3  Sujal     Jain    sujalexample@gmail.com   18
4  Chris      NaN           chris@gamil.com   50
5    NaN      NaN                       NaN  NaN
6    NaN      NaN                       NaN  NaN

In [35]:
df

   first     last                     email  age
0  Mansi  Kothari  mansikothari46@gmail.com   19
1  Manan     Jain  kotharimanan46@gmail.com   16
2  Komal  Kothari                       NaN  NaN
3  Sujal     Jain    sujalexample@gmail.com   18
4  Chris      NaN           chris@gamil.com   50
5    NaN      NaN                       NaN  NaN
6    NaN      NaN                       NaN  NaN

In [36]:
df.dropna()

   first     last                     email age
0  Mansi  Kothari  mansikothari46@gmail.com  19
1  Manan     Jain  kotharimanan46@gmail.com  16
3  Sujal     Jain    sujalexample@gmail.com  18

In [37]:
df.dropna(axis='index', how='all')

   first     last                     email  age
0  Mansi  Kothari  mansikothari46@gmail.com   19
1  Manan     Jain  kotharimanan46@gmail.com   16
2  Komal  Kothari                       NaN  NaN
3  Sujal     Jain    sujalexample@gmail.com   18
4  Chris      NaN           chris@gamil.com   50

In [38]:
df.dropna(axis='columns', how='all')

   first     last                     email  age
0  Mansi  Kothari  mansikothari46@gmail.com   19
1  Manan     Jain  kotharimanan46@gmail.com   16
2  Komal  Kothari                       NaN  NaN
3  Sujal     Jain    sujalexample@gmail.com   18
4  Chris      NaN           chris@gamil.com   50
5    NaN      NaN                       NaN  NaN
6    NaN      NaN                       NaN  NaN

In [39]:
df.dropna(axis='index', how='all', subset=['email', 'last'])

   first     last                     email  age
0  Mansi  Kothari  mansikothari46@gmail.com   19
1  Manan     Jain  kotharimanan46@gmail.com   16
2  Komal  Kothari                       NaN  NaN
3  Sujal     Jain    sujalexample@gmail.com   18
4  Chris      NaN           chris@gamil.com   50

In [40]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False
5   True   True   True   True
6   True   True   True   True

In [41]:
df.fillna('MISSING')

     first     last                     email      age
0    Mansi  Kothari  mansikothari46@gmail.com       19
1    Manan     Jain  kotharimanan46@gmail.com       16
2    Komal  Kothari                   MISSING  MISSING
3    Sujal     Jain    sujalexample@gmail.com       18
4    Chris  MISSING           chris@gamil.com       50
5  MISSING  MISSING                   MISSING  MISSING
6  MISSING  MISSING                   MISSING  MISSING

In [42]:
df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [43]:
type(np.nan)

float

In [45]:
df['age'] = df['age'].astype(float)

In [46]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

In [47]:
df

   first     last                     email   age
0  Mansi  Kothari  mansikothari46@gmail.com  19.0
1  Manan     Jain  kotharimanan46@gmail.com  16.0
2  Komal  Kothari                       NaN   NaN
3  Sujal     Jain    sujalexample@gmail.com  18.0
4  Chris      NaN           chris@gamil.com  50.0
5    NaN      NaN                       NaN   NaN
6    NaN      NaN                       NaN   NaN

In [48]:
df['age'].mean()

np.float64(25.75)