In [1]:
person = {
    "first": "Mansi",
    "last": "Kothari",
    "email": "mansikothari46@gmail.com"
}

In [2]:
people = {
    "first": ["Mansi"],
    "last": ["Kothari"],
    "email": ["mansikothari46@gmail.com"]
}

In [3]:
people = {
    "first": ["Mansi", "Manan", "Komal", "Sujal"],
    "last": ["Kothari", "Jain", "Kothari", "Jain"],
    "email": ["mansikothari46@gmail.com", "kotharimanan46@gmail.com", "komalexample@gmail.com", "sujalexample@gmail.com"]
}

In [4]:
people['email']

['mansikothari46@gmail.com',
 'kotharimanan46@gmail.com',
 'komalexample@gmail.com',
 'sujalexample@gmail.com']

In [5]:
import pandas as pd

In [37]:
df = pd.DataFrame(people)

In [7]:
df

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
1  Manan     Jain  kotharimanan46@gmail.com
2  Komal  Kothari    komalexample@gmail.com
3  Sujal     Jain    sujalexample@gmail.com

In [9]:
df['email']

0    mansikothari46@gmail.com
1    kotharimanan46@gmail.com
2      komalexample@gmail.com
3      sujalexample@gmail.com
Name: email, dtype: str

In [10]:
type(df['email'])

pandas.Series

In [11]:
df.email

0    mansikothari46@gmail.com
1    kotharimanan46@gmail.com
2      komalexample@gmail.com
3      sujalexample@gmail.com
Name: email, dtype: str

In [13]:
df[["last","email"]]

      last                     email
0  Kothari  mansikothari46@gmail.com
1     Jain  kotharimanan46@gmail.com
2  Kothari    komalexample@gmail.com
3     Jain    sujalexample@gmail.com

In [14]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [15]:
df.iloc[0]

first                       Mansi
last                      Kothari
email    mansikothari46@gmail.com
Name: 0, dtype: str

In [17]:
df.iloc[[0, 2]]

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
2  Komal  Kothari    komalexample@gmail.com

In [20]:
df.iloc[[0, 1], [1, 2]]

      last                     email
0  Kothari  mansikothari46@gmail.com
1     Jain  kotharimanan46@gmail.com

In [21]:
df

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
1  Manan     Jain  kotharimanan46@gmail.com
2  Komal  Kothari    komalexample@gmail.com
3  Sujal     Jain    sujalexample@gmail.com

In [22]:
df.loc[0]

first                       Mansi
last                      Kothari
email    mansikothari46@gmail.com
Name: 0, dtype: str

In [24]:
df.loc[[2, 3]]

   first     last                   email
2  Komal  Kothari  komalexample@gmail.com
3  Sujal     Jain  sujalexample@gmail.com

In [25]:
df.loc[[2, 3], 'email']

2    komalexample@gmail.com
3    sujalexample@gmail.com
Name: email, dtype: str

In [27]:
df.loc[[2, 3], ['first','last']]

   first     last
2  Komal  Kothari
3  Sujal     Jain

In [38]:
df

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
1  Manan     Jain  kotharimanan46@gmail.com
2  Komal  Kothari    komalexample@gmail.com
3  Sujal     Jain    sujalexample@gmail.com

In [39]:
df.set_index('email', inplace=True)

In [40]:
df

                          first     last
email
mansikothari46@gmail.com  Mansi  Kothari
kotharimanan46@gmail.com  Manan     Jain
komalexample@gmail.com    Komal  Kothari
sujalexample@gmail.com    Sujal     Jain

In [41]:
df.index

Index(['mansikothari46@gmail.com', 'kotharimanan46@gmail.com',
       'komalexample@gmail.com', 'sujalexample@gmail.com'],
      dtype='str', name='email')

In [42]:
df.loc['komalexample@gmail.com']

first      Komal
last     Kothari
Name: komalexample@gmail.com, dtype: str

In [44]:
df.iloc[2]

first      Komal
last     Kothari
Name: komalexample@gmail.com, dtype: str

In [45]:
df.reset_index(inplace=True)
df

                      email  first     last
0  mansikothari46@gmail.com  Mansi  Kothari
1  kotharimanan46@gmail.com  Manan     Jain
2    komalexample@gmail.com  Komal  Kothari
3    sujalexample@gmail.com  Sujal     Jain